"use client"
import { useEffect, useRef, useState } from "react"
import { Button } from "@/components/ui/button"
interface LiveScanScreenProps { onBack: () => void; onFinish: () => void; sessionId: string }
export function LiveScanScreen({ onBack, onFinish, sessionId }: LiveScanScreenProps) {
const [isPaused,setIsPaused]=useState(false); const [uploadError,setUploadError]=useState<string|null>(null); const [accepted,setAccepted]=useState(0)
const videoRef=useRef<HTMLVideoElement|null>(null); const canvasRef=useRef<HTMLCanvasElement|null>(null); const inFlightRef=useRef(false); const queuedPayloadRef=useRef<string|null>(null)
useEffect(()=>{let stream:MediaStream|null=null; navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'}},audio:false}).then(async s=>{stream=s; if(videoRef.current){videoRef.current.srcObject=s; await videoRef.current.play()}}).catch((e)=>setUploadError(String(e))); return ()=>stream?.getTracks().forEach(t=>t.stop())},[])
useEffect(()=>{ if(isPaused) return; const it=setInterval(()=>{const v=videoRef.current,c=canvasRef.current;if(!v||!c||v.readyState<2)return; c.width=v.videoWidth;c.height=v.videoHeight; c.getContext('2d')?.drawImage(v,0,0); const base64=c.toDataURL('image/jpeg',0.65).split(',')[1]; const payload=JSON.stringify({image_b64:base64,frame_id:'ios_camera',room_id:'room-1',guidance_hint:'look-corners',ts:Date.now()/1000}); if(inFlightRef.current){queuedPayloadRef.current=payload;return;} inFlightRef.current=true; const send=async (b:string)=>{try{const r=await fetch(`/api/scan/sessions/${sessionId}/frame`,{method:'POST',headers:{'Content-Type':'application/json'},body:b}); if(!r.ok) setUploadError(`Upload failed (${r.status})`); else {setUploadError(null); setAccepted((x)=>x+1)} const q=queuedPayloadRef.current; queuedPayloadRef.current=null; if(q) await send(q)} finally{inFlightRef.current=false}}; void send(payload)},1000); return ()=>clearInterval(it)},[isPaused,sessionId])
return <div><video ref={videoRef} playsInline muted/><canvas ref={canvasRef} className='hidden'/><p>accepted: {accepted}</p>{uploadError&&<p>{uploadError}</p>}<Button onClick={()=>fetch(`/api/scan/sessions/${sessionId}/event`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({event_type:'room_finished',room_id:'room-1'})})}>Finish Room</Button><Button onClick={onFinish}>Finish All</Button><Button onClick={onBack}>Back</Button></div>
}
